name: Deploy portfolio website to GitHub pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          EMAILJS_PUBLIC_KEY: ${{secrets.EMAILJS_PUBLIC_KEY}},
          EMAILJS_SERVICE_ID: ${{secrets.EMAILJS_SERVICE_ID}},
          EMAILJS_TEMPLATE_ID: ${{secrets.EMAILJS_TEMPLATE_ID}}
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: "github-pages"
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          artifact_name: "github-pages"
